model = "gpt-5-codex"
model_reasoning_effort = "medium"

[tui]
notifications = true

[tools]
web_search = true

[mcp_servers.chrome-dev-tools]
command = "pnpm"
args = ["dlx", "chrome-devtools-mcp@latest"]
