{
  config,
  lib,
  pkgs,
  ...
}:

{
  config = lib.mkIf config.stylix.enable (
    let
      cfg = config.stylix.targets.vicinae;
      colors = config.lib.stylix.colors.withHashtag;
      polarity = config.stylix.polarity;

      themeFile = (pkgs.formats.toml { }).generate "stylix.toml" {
        meta = {
          version = 1;
          name = "stylix";
          description = "Theme generated by stylix";
          variant = if polarity == "either" then "light" else polarity;
        };

        colors = {
          core = {
            background = colors.base00;
            foreground = colors.base05;
            secondary_background = colors.base01;
            border = colors.base02;
            accent = colors.base0D;
          };

          accents = {
            blue = colors.base0D;
            green = colors.base0B;
            magenta = colors.base0E;
            orange = colors.base09;
            purple = colors.base0E;
            red = colors.base08;
            yellow = colors.base0A;
            cyan = colors.base0C;
          };

          input = {
            background = colors.base01;
            border = colors.base02;
            border_focus = colors.base0D;
            foreground = colors.base05;
            placeholder = colors.base03;
            selection.background = colors.base02;
          };

          list.item = {
            selection.background = colors.base02;
            selection.secondary_background = colors.base03;
            hover.background = colors.base01;
          };
        };
      };
    in
    lib.mkIf cfg.enable {
      home.file.".local/share/vicinae/themes/stylix.toml".source = themeFile;
    }
  );
}
