model = "gpt-5-codex"
model_reasoning_effort = "medium"

[tui]
notifications = true

[tools]
web_search = true

[mcp_servers.chrome-dev-tools]
command = "bunx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.context7]
command = "bunx"
args = ["@upstash/context7-mcp", "--api-key", "$CONTEXT7_API_KEY"]
